# Site settings
title: All in いち | Conversations Archive
email: ichi@atrajit.one
description: >-
  Your personal archive for conversations ✨ | Save, organize, and revisit your chats
  A collaborative space where friends share and explore meaningful exchanges
baseurl: "" # Only if using project site, leave empty for personal site
url: "https://www.atrajit.one"

# Author information
author:
  name: All in いち
  email: ichi@atrajit.one
  tagline: "Chats | Shared Wisdom | Friend Quest"
  subtitle: "Where Intelligence Meets Curiosity"
  bio: >-
    A collaborative platform for storing and sharing meaningful conversations.
    Join our friend quest to explore the depth of human dialogue and discover
    the wisdom hidden in everyday chats.

# Tech Stack - Removed since this is now a chat storage site
# Keeping the structure for potential future features

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Kramdown settings for math
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Navigation - Simplified for chat storage site
navigation:
  - title: Home
    url: /
    icon: "home"
  - title: Chat Archive
    url: /posts/
    icon: "message-circle"

# Theme settings - Minimal chat archive theme
theme_color: "#10a37f"
accent_color: "#19c37d"

# Social links - Updated for atrajit.one domain
social:
  email: ichi@atrajit.one

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: page

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Ads completely removed for clean experience
